require 'faker'
# create users

user1 = User.create(username: Faker::Internet.user_name ,password:"password")
user2 = User.create(username: Faker::Internet.user_name ,password:"password")
user3 = User.create(username: Faker::Internet.user_name ,password:"password")
user4 = User.create(username: Faker::Internet.user_name ,password:"password")
user5 = User.create(username: Faker::Internet.user_name ,password:"password")
user6 = User.create(username: Faker::Internet.user_name ,password:"password")
user7 = User.create(username: Faker::Internet.user_name ,password:"password")
user8 = User.create(username: Faker::Internet.user_name ,password:"password")
user9 = User.create(username: Faker::Internet.user_name ,password:"password")
user10 = User.create(username: Faker::Internet.user_name ,password:"password")
user11 = User.create(username: Faker::Internet.user_name ,password:"password")
user12 = User.create(username: Faker::Internet.user_name ,password:"password")

# create questions
Question.create(title: "Who?", body: "How long should do it for?", user_id: 1)
Question.create(title: "What?", body: "HELP!", user_id: 2)
Question.create(title: "Where?", body: "Which one?", user_id: 3)
Question.create(title: "When?", body: "Best brand?", user_id: 4)
Question.create(title: "Why?", body: "I it's haunted... anyone else?", user_id: 5)
Question.create(title: "Where the party at?", body: "What are the best ways to get it done?", user_id: 6)
Question.create(title: "Wheezy?", body: "Anyone else give shoutouts?", user_id: 2)
Question.create(title: "When will I grow up?", body: "I'm trying to make my own. Does anyone have recommend any tutorials?", user_id: 2)
Question.create(title: "What's for dinner?", body: "When was it created?", user_id: 3)

Question.create(body: Faker::Hacker.say_something_smart, user_id: 1)
Question.create(body: Faker::Hacker.say_something_smart, user_id: 2)
Question.create(body: Faker::Hacker.say_something_smart, user_id: 3)
Question.create(body: Faker::Hacker.say_something_smart, user_id: 4)
Question.create(body: Faker::Hacker.say_something_smart, user_id: 5)
Question.create(body: Faker::Hacker.say_something_smart, user_id: 6)
Question.create(body: Faker::Hacker.say_something_smart, user_id: 2)
Question.create(body: Faker::Hacker.say_something_smart, user_id: 2)
Question.create(body: Faker::Hacker.say_something_smart, user_id: 3)

# create answers
Answer.create(body: "I would recommend 12", user_id:2, question_id: 1)
Answer.create(body: "Call 1-800-411-PAIN", user_id:3, question_id: 2)
Answer.create(body: "I personally like them all.", user_id:4, question_id: 3)
Answer.create(body: "I've heard it's a pretty realible brand.", user_id:5, question_id: 4)
Answer.create(body: "Yes. I think it is a bit common.", user_id:6, question_id: 5)
Answer.create(body: "They are magical.", user_id:1, question_id: 6)
Answer.create(body: "Check their website out.", user_id:3, question_id: 7)
Answer.create(body: "I don't think you should ask that.", user_id:4, question_id: 8)

# create comments
Comment.create(body: Faker::Hipster.sentence, commentable_id: 1, commentable_type: "Question", user_id:1)
Comment.create(body: Faker::Hipster.sentence, commentable_id: 2, commentable_type: "Answer", user_id:1)
Comment.create(body: Faker::Hipster.sentence, commentable_id: 3, commentable_type: "Answer", user_id:2)
Comment.create(body: Faker::Hipster.sentence, commentable_id: 6, commentable_type: "Question", user_id:2)
Comment.create(body: Faker::Hipster.sentence, commentable_id: 11, commentable_type: "Question", user_id:1)
Comment.create(body: Faker::Hipster.sentence, commentable_id: 12, commentable_type: "Answer", user_id:1)
Comment.create(body: Faker::Hipster.sentence, commentable_id: 9, commentable_type: "Answer", user_id:2)
Comment.create(body: Faker::Hipster.sentence, commentable_id: 8, commentable_type: "Question", user_id:2)

Comment.create(body: "I would also love to know!", commentable_id: 1, commentable_type: "Question", user_id:6)
Comment.create(body: "Yes, they are very reliable.", commentable_id: 2, commentable_type: "Answer", user_id:4)
Comment.create(body: "I second that. I think it tastes better.", commentable_id: 3, commentable_type: "Answer", user_id:1)
Comment.create(body: "What type do you have?", commentable_id: 6, commentable_type: "Question", user_id:1)
Comment.create(body: "I would also love to know!", commentable_id: 1, commentable_type: "Question", user_id:12)
Comment.create(body: "Yes, they are very reliable.", commentable_id: 2, commentable_type: "Answer", user_id:9)
Comment.create(body: "I second that. I think it tastes better.", commentable_id: 3, commentable_type: "Answer", user_id:11)
Comment.create(body: "What type do you have?", commentable_id: 6, commentable_type: "Question", user_id:7)

Vote.create(up_down: 1, user_id: 4, votable_id:5, votable_type: "Answer")
Vote.create(up_down: 1, user_id: 5, votable_id:2, votable_type: "Question")
Vote.create(up_down: -1, user_id: 1, votable_id:4, votable_type: "Answer")
Vote.create(up_down: -1, user_id: 2, votable_id:3, votable_type: "Answer")
Vote.create(up_down: 1, user_id: 3, votable_id:5, votable_type: "Answer")
Vote.create(up_down: 1, user_id: 2, votable_id:5, votable_type: "Answer")

Vote.create(up_down: 1, user_id: 8, votable_id:5, votable_type: "Answer")
Vote.create(up_down: 1, user_id: 10, votable_id:2, votable_type: "Question")
Vote.create(up_down: -1, user_id: 9, votable_id:4, votable_type: "Answer")
Vote.create(up_down: -1, user_id: 7, votable_id:3, votable_type: "Answer")
Vote.create(up_down: 1, user_id: 11, votable_id:5, votable_type: "Answer")
Vote.create(up_down: 1, user_id: 7, votable_id:5, votable_type: "Answer")
